created TalkModule feature file and Page class
NatalyaKhvan/LeoSymund pull request #9
Opened 2023-07-18 08:20 UTC by yfarangis

2023-07-18 16:47 UTC, aminjh approved these changes

2023-07-19 18:09 UTC, NatalyaKhvan requested changes
I just see Talk module page. Where are feature and stepDefs?

2023-07-19 18:16 UTC, NatalyaKhvan commented on src/test/resources/features/Talk.feature
lines 22 and 25 are unused and could be deleted ;)

2023-07-19 18:23 UTC, yfarangis commented on src/test/resources/features/Talk.feature
I was experimenting with classes

2023-07-19 18:26 UTC, NatalyaKhvan approved these changes

2023-07-19 18:26 UTC, merged